[theme]
base="dark"
primaryColor="#4CAF50"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
